server:
  port: 8082
  servlet:
    context-path: /


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jgdb?serverTimezone=GMT&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  type-aliases-package: com.hbnu.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.hbnu.dao: debug